### ISSUE TITLE
Problem with the Overlay

### ISSUE THREAD

**Issue by Confuseed** [imperial-mod/overlay#2]
I downloaded the overlay and ran it. I filled in the necessary gaps (nickname and api) and tested the overlay. At the start it didn't show anything (although i joined as the first person). I tried many more times, and it worked only once, when I met a nicked player. It showed only their nicked ign and a note that they are nicked. Do you know what's the problem?

**Comment by Zxnii** [comment]
overlay no longer works, chat stats still works but neither will be receiving any official support see the [discord](https://discord.gg/rfsPr2kBvv) for more info
